[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/s/:splat"
  status = 200

[[redirects]]
  from = "/m/*"
  to = "/.netlify/functions/m/:splat"
  status = 200
